#!/usr/bin/env python3
"""Generate vita/src/game/item_spawns.h from the Blitz sources.

Extracts:
 - item templates from CreateItemTemplate(...) in Loading_Core.bb
   (display name, model, texture override, world scale), and
 - literal-coordinate item spawns from FillRoom's CreateItem(...) calls
   in Rooms_Core.bb, attributed to the enclosing Case r_<room> label.

Spawns using runtime expressions (entity positions, Rand, loops) are
skipped; this captures the fixed placements like the storage shelves.

Run from the repo root:  python3 vita/tools/extract_items.py
"""

import re
import sys

ROOMS = "Source Code/Rooms_Core.bb"
LOADING = "Source Code/Loading_Core.bb"
OUT = "vita/src/game/item_spawns.h"

# ---- item templates ----
# Anchor on display-name, it_<id>, "<model>.b3d" since the first
# argument (GetLocalString(...)) contains commas.
tpl_re = re.compile(
    r'"([^"]+)"\s*,\s*\w+\s*,\s*"([^"]+\.b3d)"\s*,'
    r'\s*"([^"]*)"\s*,\s*"([^"]*)"\s*,\s*([0-9.eE-]+)\s*,\s*\w+\s*'
    r'(?:,\s*"([^"]*)")?')

templates = {}
for line in open(LOADING, encoding="latin-1"):
    if "CreateItemTemplate(" not in line:
        continue
    m = tpl_re.search(line)
    if m:
        name, model, inv = m.group(1), m.group(2), m.group(3)
        doc, scale, tex = m.group(4), m.group(5), m.group(6)
        # ImgPath$ is only a readable page for paper-class items; for
        # equipment (radio, navigator, e-reader...) it is the equipped
        # HUD overlay sprite and must not become a document.
        if model.lower() not in ("paper.b3d", "note.b3d", "badge.b3d"):
            doc = ""
        if name not in templates:
            templates[name] = (model, tex or "", float(scale), inv or "",
                               doc or "")

# ---- spawns ----
case_re = re.compile(r'^\s*Case\s+(r_[\w, \t]+)')
item_re = re.compile(r'CreateItem\("([^"]+)"\s*,\s*\w+\s*,([^)]*)\)')
num_expr = re.compile(r'^[0-9+\-*/. ()\t]+$')

def eval_coord(expr):
    e = expr.strip()
    e = e.replace("r\\x", "0").replace("r\\y", "0").replace("r\\z", "0")
    e = e.replace("RoomScale", "1")
    if not e or not num_expr.match(e):
        return None
    try:
        return float(eval(e))
    except Exception:
        return None

spawns = []
rooms = []
for line in open(ROOMS, encoding="latin-1"):
    cm = case_re.match(line)
    if cm:
        rooms = [r.strip()[2:] for r in cm.group(1).split(",")
                 if r.strip().startswith("r_")]
        continue
    im = item_re.search(line)
    if im and rooms:
        name = im.group(1)
        args = im.group(2).split(",")
        if len(args) < 3 or name not in templates:
            continue
        x = eval_coord(args[0])
        y = eval_coord(args[1])
        z = eval_coord(args[2])
        if x is None or y is None or z is None:
            continue
        if x == 0.0 and y == 0.0 and z == 0.0:
            continue  # positioned by script elsewhere
        for room in rooms:
            spawns.append((room, name, x, y, z))

used = sorted({s[1] for s in spawns} | {
    "Level 1 key Card", "Level 3 key Card", "Level 5 key Card"})

with open(OUT, "w") as f:
    f.write("/* Generated by vita/tools/extract_items.py - do not edit.\n"
            " * Item templates from Loading_Core.bb and literal-coordinate\n"
            " * FillRoom spawns from Rooms_Core.bb (room-local raw units). */\n"
            "#ifndef VITA_GAME_ITEM_SPAWNS_H\n"
            "#define VITA_GAME_ITEM_SPAWNS_H\n\n"
            "typedef struct {\n"
            "    const char *name;\n"
            "    const char *model;\n"
            "    const char *texture; /* \"\" = model default */\n"
            "    const char *invIcon;\n"
            "    const char *docImage; /* \"\" = not a readable document */\n"
            "    float worldScale;\n"
            "} ItemTemplateDef;\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    const char *item;\n"
            "    float x, y, z; /* room-local raw units */\n"
            "} ItemSpawnDef;\n\n")
    def cf(v):
        s = "%.9g" % v
        if "." not in s and "e" not in s and "E" not in s:
            s += ".0"
        return s + "f"

    f.write("static const ItemTemplateDef ITEM_TEMPLATES[] = {\n")
    for name in used:
        if name in templates:
            model, tex, scale, inv, doc = templates[name]
            f.write('    { "%s", "%s", "%s", "%s", "%s", %s },\n'
                    % (name, model, tex, inv, doc, cf(scale)))
    f.write("};\n\n")
    f.write("static const ItemSpawnDef ITEM_SPAWNS[] = {\n")
    for room, name, x, y, z in spawns:
        f.write('    { "%s", "%s", %s, %s, %s },\n'
                % (room, name, cf(x), cf(y), cf(z)))
    f.write("};\n\n#endif\n")

print("templates used:", len(used), "spawns:", len(spawns))
