#!/usr/bin/env python3
"""Generate vita/src/game/room_doors.h from the Blitz sources.

Extracts room-internal doors from FillRoom's CreateDoor(...) calls in
Rooms_Core.bb (containment chamber doors, elevator covers, locked
service doors), attributed to the enclosing Case r_<room> label.
These are what the grid-door pass (between rooms) cannot produce; a
room like cont2_427_714_860_1025 creates eight of them.

Coordinates using runtime expressions (entity positions, Rand, loops)
are skipped; this captures the fixed placements. A `d\\Locked = 1`
within the lines following an assigned CreateDoor marks the door
locked.

Run from the repo root:  python3 vita/tools/extract_doors.py
"""

import re

ROOMS = "Source Code/Rooms_Core.bb"
OUT = "vita/src/game/room_doors.h"

DOOR_TYPES = {
    "DEFAULT_DOOR": 0, "ELEVATOR_DOOR": 1, "HEAVY_DOOR": 2, "BIG_DOOR": 3,
    "OFFICE_DOOR": 4, "WOODEN_DOOR": 5, "ONE_SIDED_DOOR": 6,
}
# Items_Core.bb: KEY_CARD_n constants; negative KEY_* are special
# scanners the port cannot open, mapped to locked.
KEYCARDS = {
    "KEY_MISC": 0, "KEY_CARD_0": 0, "KEY_CARD_1": 1, "KEY_CARD_2": 2,
    "KEY_CARD_3": 3, "KEY_CARD_4": 4, "KEY_CARD_5": 5, "KEY_CARD_6": 6,
    "KEY_CARD_OMNI": 6, "KEY_005": 0,
}
LOCKED_KEYS = {"KEY_HAND_WHITE", "KEY_HAND_BLACK", "KEY_HAND_YELLOW",
               "KEY_860", "KEY_KEY"}

case_re = re.compile(r'^\s*Case\s+(r_[\w, \t]+)')
door_re = re.compile(r'CreateDoor\(\s*r\s*,([^)]*)\)')
num_expr = re.compile(r'^[0-9+\-*/. ()\t]+$')


def eval_coord(expr):
    e = expr.strip()
    e = e.replace("r\\x", "0").replace("r\\y", "0").replace("r\\z", "0")
    e = e.replace("RoomScale", "1")
    if not e or not num_expr.match(e):
        return None
    try:
        return float(eval(e))
    except Exception:
        return None


def split_args(argstr):
    # No nested parens in the calls we accept (door_re stops at ')').
    return [a.strip() for a in argstr.split(",")]


doors = []
rooms = []
lines = open(ROOMS, encoding="latin-1").readlines()
for li, line in enumerate(lines):
    cm = case_re.match(line)
    if cm:
        rooms = [r.strip()[2:] for r in cm.group(1).split(",")
                 if r.strip().startswith("r_")]
        continue
    dm = door_re.search(line)
    if not dm or not rooms:
        continue
    args = split_args(dm.group(1))
    if len(args) < 4:
        continue
    x = eval_coord(args[0])
    y = eval_coord(args[1])
    z = eval_coord(args[2])
    ang = eval_coord(args[3])
    if x is None or y is None or z is None or ang is None:
        continue
    is_open = len(args) > 4 and args[4].strip() == "True"
    dtype = DOOR_TYPES.get(args[5].strip(), 0) if len(args) > 5 else 0
    locked = 0
    keycard = 0
    if len(args) > 6:
        k = args[6].strip()
        if k in LOCKED_KEYS:
            locked = 1
        else:
            keycard = KEYCARDS.get(k, 0)
    # `d\Locked = 1` on the assigned door within the next few lines.
    if "=" in line.split("CreateDoor")[0]:
        for follow in lines[li + 1:li + 5]:
            if case_re.match(follow) or "CreateDoor" in follow:
                break
            if re.search(r'\\Locked\s*=\s*1', follow):
                locked = 1
                break
    for room in rooms:
        doors.append((room, x, y, z, ang % 360.0, is_open, dtype,
                      keycard, locked))


def cf(v):
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


with open(OUT, "w") as f:
    f.write("/* Generated by vita/tools/extract_doors.py - do not edit.\n"
            " * Room-internal doors from FillRoom's literal-coordinate\n"
            " * CreateDoor calls in Rooms_Core.bb (room-local raw units;\n"
            " * type: 0 default 1 elevator 2 heavy 3 big 4 office 5 wooden\n"
            " * 6 one-sided). */\n"
            "#ifndef VITA_GAME_ROOM_DOORS_H\n"
            "#define VITA_GAME_ROOM_DOORS_H\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    float x, y, z;    /* room-local raw units */\n"
            "    float angleDeg;   /* Blitz yaw within the room */\n"
            "    unsigned char open, type, keycard, locked;\n"
            "} RoomDoorDef;\n\n"
            "static const RoomDoorDef ROOM_DOORS[] = {\n")
    for room, x, y, z, ang, is_open, dtype, keycard, locked in doors:
        f.write('    { "%s", %s, %s, %s, %s, %d, %d, %d, %d },\n'
                % (room, cf(x), cf(y), cf(z), cf(ang), 1 if is_open else 0,
                   dtype, keycard, locked))
    f.write("};\n\n#endif\n")

print("room doors:", len(doors))
