#!/usr/bin/env python3
"""Generate vita/src/game/room_decals.h from the Blitz sources.

Extracts FillRoom's CreateDecal(...) calls in Rooms_Core.bb - the static
blood/corrosion/water/symbol splats scattered on room floors and walls.
Only literal-coordinate, literal-ID placements are captured; calls whose
ID or coordinates come from loop variables (xTemp/zTemp), Temp, or Rand()
are runtime and skipped.

CreateDecal(ID, x, y, z, Pitch, Yaw, Roll, Size=1, Alpha=1, FX=0,
            BlendMode=1, R, G, B) - coordinates are room-local raw units.
Rnd(a, b) size/alpha use the midpoint; Rnd(360.0) yaw becomes 0 (a fixed
spin per placement is not worth reproducing).

Run from the repo root:  python3 vita/tools/extract_decals.py
"""

import re

ROOMS = "Source Code/Rooms_Core.bb"
OUT = "vita/src/game/room_decals.h"

# Decal IDs (Loading_Core.bb). KETER (21) / APOLLYON (22) are
# achievement-gated and normally absent, so they are dropped.
DECAL_IDS = {
    "DECAL_CORROSIVE_1": 0, "DECAL_CORROSIVE_2": 1,
    "DECAL_BLOOD_1": 2, "DECAL_BLOOD_2": 3, "DECAL_BLOOD_3": 4,
    "DECAL_BLOOD_4": 5, "DECAL_BLOOD_5": 6, "DECAL_BLOOD_6": 7,
    "DECAL_PD_1": 8, "DECAL_PD_2": 9, "DECAL_PD_3": 10,
    "DECAL_PD_4": 11, "DECAL_PD_5": 12, "DECAL_PD_6": 13,
    "DECAL_BULLET_HOLE_1": 14, "DECAL_BULLET_HOLE_2": 15,
    "DECAL_BLOOD_DROP_1": 16, "DECAL_BLOOD_DROP_2": 17,
    "DECAL_427": 18, "DECAL_409": 19, "DECAL_WATER": 20,
}
DROP_IDS = {"DECAL_KETER": 21, "DECAL_APOLLYON": 22}

case_re = re.compile(r'^\s*Case\s+(r_[\w, \t]+)')
decal_re = re.compile(r'CreateDecal\(([^)]*)\)')
num_expr = re.compile(r'^[0-9+\-*/. ()\t]+$')
rnd_re = re.compile(r'Rnd\(\s*([0-9.]+)\s*,\s*([0-9.]+)\s*\)')


def num(expr, default=None):
    e = expr.strip()
    m = rnd_re.fullmatch(e)
    if m:                       # Rnd(a, b) -> midpoint
        return (float(m.group(1)) + float(m.group(2))) / 2.0
    if e.startswith("Rnd("):    # Rnd(360.0) spin -> 0
        return 0.0
    e = e.replace("r\\x", "0").replace("r\\y", "0").replace("r\\z", "0")
    e = e.replace("RoomScale", "1")
    if not e or not num_expr.match(e):
        return None
    try:
        return float(eval(e))
    except Exception:
        return None


decals = []
rooms = []
skipped = 0
for line in open(ROOMS, encoding="latin-1"):
    cm = case_re.match(line)
    if cm:
        rooms = [r.strip()[2:] for r in cm.group(1).split(",")
                 if r.strip().startswith("r_")]
        continue
    if not rooms:
        continue
    dm = decal_re.search(line)
    if not dm:
        continue
    a = [x.strip() for x in dm.group(1).split(",")]
    if len(a) < 4:
        continue
    did = DECAL_IDS.get(a[0])
    if did is None:
        skipped += 1        # Temp / Rand()/ i+7 / KETER / APOLLYON
        continue
    x, y, z = num(a[1]), num(a[2]), num(a[3])
    pitch = num(a[4]) if len(a) > 4 else 0.0
    yaw = num(a[5]) if len(a) > 5 else 0.0
    roll = num(a[6]) if len(a) > 6 else 0.0
    if None in (x, y, z, pitch, yaw, roll):
        skipped += 1
        continue
    size = num(a[7]) if len(a) > 7 else 1.0
    alpha = num(a[8]) if len(a) > 8 else 1.0
    blend = num(a[10]) if len(a) > 10 else 1.0
    if size is None:
        size = 1.0
    if alpha is None:
        alpha = 1.0
    blend = int(blend) if blend else 1
    for room in rooms:
        decals.append((room, did, x, y, z, pitch, yaw % 360.0, roll,
                       size, alpha, blend))


def cf(v):
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


with open(OUT, "w") as f:
    f.write("/* Generated by vita/tools/extract_decals.py - do not edit.\n"
            " * FillRoom's static CreateDecal splats (room-local raw\n"
            " * units; Blitz euler degrees; blend 1 alpha 2 multiply\n"
            " * 3 additive). */\n"
            "#ifndef VITA_GAME_ROOM_DECALS_H\n"
            "#define VITA_GAME_ROOM_DECALS_H\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    unsigned char id;\n"
            "    float x, y, z;\n"
            "    float pitch, yaw, roll;\n"
            "    float size, alpha;\n"
            "    unsigned char blend;\n"
            "} RoomDecalDef;\n\n"
            "static const RoomDecalDef ROOM_DECALS[] = {\n")
    for room, did, x, y, z, p, yw, rl, sz, al, bl in decals:
        f.write('    { "%s", %d, %s, %s, %s, %s, %s, %s, %s, %s, %d },\n'
                % (room, did, cf(x), cf(y), cf(z), cf(p), cf(yw), cf(rl),
                   cf(sz), cf(al), bl))
    f.write("};\n\n#endif\n")

print("room decals:", len(decals), "skipped (runtime/achievement):", skipped)
