#!/usr/bin/env python3
"""Generate vita/src/game/room_cameras.h from the Blitz sources.

Extracts FillRoom's CreateSecurityCam(...) calls in Rooms_Core.bb - the
wall security cameras (a base + a swivelling head with a blinking red
light). The live monitor feed / SCP-079 broadcast is not ported; only
the visible camera prop and its motion are.

CreateSecurityCam(room, x, y, z, Pitch1, Screen=False, x2, y2, z2,
                  Pitch2, Yaw2, Roll2) - room-local raw units, Pitch1 is
the head's downward tilt. The head's yaw base (sc\\Angle), sweep
amplitude (sc\\Turn) and sc\\FollowPlayer are set on the lines just after
the call, so we scan a few follow-up lines for them (also colon-chained,
e.g. `sc\\Angle = 180.0 : sc\\Turn = 45.0`).

Literal-coordinate placements only; loop/Rand ones are skipped.

Run from the repo root:  python3 vita/tools/extract_cameras.py
"""

import re

ROOMS = "Source Code/Rooms_Core.bb"
OUT = "vita/src/game/room_cameras.h"

case_re = re.compile(r'^\s*Case\s+(r_[\w, \t]+)')
cam_re = re.compile(r'CreateSecurityCam\(\s*r\s*,([^)]*)\)')
num_expr = re.compile(r'^[0-9+\-*/. ()\t]+$')
angle_re = re.compile(r'sc\\Angle\s*=\s*([0-9.\-]+)')
turn_re = re.compile(r'sc\\Turn\s*=\s*([0-9.\-]+)')
follow_re = re.compile(r'sc\\FollowPlayer\s*=\s*True')


def ev(expr):
    e = expr.strip()
    e = e.replace("r\\x", "0").replace("r\\y", "0").replace("r\\z", "0")
    e = e.replace("RoomScale", "1")
    if not e or not num_expr.match(e):
        return None
    try:
        return float(eval(e))
    except Exception:
        return None


cams = []
rooms = []
lines = open(ROOMS, encoding="latin-1").readlines()
for li, line in enumerate(lines):
    cm = case_re.match(line)
    if cm:
        rooms = [r.strip()[2:] for r in cm.group(1).split(",")
                 if r.strip().startswith("r_")]
        continue
    if not rooms:
        continue
    m = cam_re.search(line)
    if not m:
        continue
    a = [x.strip() for x in m.group(1).split(",")]
    if len(a) < 4:
        continue
    x, y, z = ev(a[0]), ev(a[1]), ev(a[2])
    pitch = ev(a[3]) if len(a) > 3 else 0.0
    if None in (x, y, z, pitch):
        continue
    # Screen=True cameras carry a monitor: CreateSecurityCam(room, x1, y1,
    # z1, Pitch1, Screen, x2, y2, z2, Pitch2, Yaw2, Roll2). Capture the
    # monitor's transform so the port can render the feed screen.
    screen = 1 if (len(a) > 4 and a[4] == "True") else 0
    mx = my = mz = mpitch = myaw = mroll = 0.0
    if screen and len(a) >= 8:
        mx = ev(a[5]) or 0.0
        my = ev(a[6]) or 0.0
        mz = ev(a[7]) or 0.0
        mpitch = ev(a[8]) if len(a) > 8 else 0.0
        myaw = ev(a[9]) if len(a) > 9 else 0.0
        mroll = ev(a[10]) if len(a) > 10 else 0.0
        if None in (mpitch, myaw, mroll):
            mpitch = myaw = mroll = 0.0
    # Follow-up attributes on this and the next few lines.
    angle, turn, follow = 0.0, 0.0, 0
    for follow_line in lines[li:li + 5]:
        if follow_line is not line and cam_re.search(follow_line):
            break
        if case_re.match(follow_line):
            break
        am = angle_re.search(follow_line)
        if am:
            angle = float(am.group(1))
        tm = turn_re.search(follow_line)
        if tm:
            turn = float(tm.group(1))
        if follow_re.search(follow_line):
            follow = 1
    for room in rooms:
        cams.append((room, x, y, z, pitch, angle % 360.0, turn, follow,
                     screen, mx, my, mz, mpitch, myaw % 360.0, mroll))


def cf(v):
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


with open(OUT, "w") as f:
    f.write("/* Generated by vita/tools/extract_cameras.py - do not edit.\n"
            " * FillRoom's security cameras (room-local raw units; Blitz\n"
            " * degrees). pitch = head tilt, angle = head yaw base (added\n"
            " * to the room angle), turn = sweep amplitude (0 = static),\n"
            " * follow = track the player. screen = 1 if it feeds a monitor\n"
            " * at (mx,my,mz) with orientation (mpitch,myaw,mroll). */\n"
            "#ifndef VITA_GAME_ROOM_CAMERAS_H\n"
            "#define VITA_GAME_ROOM_CAMERAS_H\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    float x, y, z;\n"
            "    float pitch, angle, turn;\n"
            "    unsigned char follow;\n"
            "    unsigned char screen;\n"
            "    float mx, my, mz;\n"
            "    float mpitch, myaw, mroll;\n"
            "} RoomCameraDef;\n\n"
            "static const RoomCameraDef ROOM_CAMERAS[] = {\n")
    for (room, x, y, z, p, ang, turn, follow, screen, mx, my, mz,
         mp, myw, mrl) in cams:
        f.write('    { "%s", %s, %s, %s, %s, %s, %s, %d, %d, '
                '%s, %s, %s, %s, %s, %s },\n'
                % (room, cf(x), cf(y), cf(z), cf(p), cf(ang), cf(turn),
                   follow, screen, cf(mx), cf(my), cf(mz), cf(mp), cf(myw),
                   cf(mrl)))
    f.write("};\n\n#endif\n")

nscreen = sum(1 for c in cams if c[8])
print("cameras:", len(cams), "with screen:", nscreen)
