#!/usr/bin/env python3
"""Generate vita/src/game/room_fixtures.h from the Blitz sources.

Extracts room-internal fixtures from FillRoom in Rooms_Core.bb:
 - CreateLever(r, x, y, z, rotation, turnedOn)  -> a wall lever (base
   + handle, the handle flips between on/off), and
 - standalone CreateButton(id, x, y, z, pitch, yaw, roll, r\\OBJ, locked)
   assigned to r\\Objects[..] (buttons parented to the room, not to a
   door - the door buttons come from extract_doors.py).

Literal-coordinate placements only; runtime expressions are skipped.
Coordinates are room-local raw units.

Run from the repo root:  python3 vita/tools/extract_fixtures.py
"""

import re

ROOMS = "Source Code/Rooms_Core.bb"
OUT = "vita/src/game/room_fixtures.h"

BUTTON_TYPES = {
    "BUTTON_DEFAULT": 0, "BUTTON_KEYCARD": 1, "BUTTON_KEYPAD": 2,
    "BUTTON_SCANNER": 3, "BUTTON_ELEVATOR": 4,
}

case_re = re.compile(r'^\s*Case\s+(r_[\w, \t]+)')
lever_re = re.compile(r'CreateLever\(\s*r\s*,([^)]*)\)')
button_re = re.compile(r'Objects\[\d+\]\s*=\s*CreateButton\(([^)]*)\)')
num_expr = re.compile(r'^[0-9+\-*/. ()\t]+$')


def ev(expr):
    e = expr.strip()
    e = e.replace("r\\x", "0").replace("r\\y", "0").replace("r\\z", "0")
    e = e.replace("RoomScale", "1")
    if not e or not num_expr.match(e):
        return None
    try:
        return float(eval(e))
    except Exception:
        return None


levers = []
buttons = []
rooms = []
for line in open(ROOMS, encoding="latin-1"):
    cm = case_re.match(line)
    if cm:
        rooms = [r.strip()[2:] for r in cm.group(1).split(",")
                 if r.strip().startswith("r_")]
        continue
    if not rooms:
        continue

    lm = lever_re.search(line)
    if lm:
        a = [x.strip() for x in lm.group(1).split(",")]
        if len(a) >= 3:
            x, y, z = ev(a[0]), ev(a[1]), ev(a[2])
            rot = ev(a[3]) if len(a) > 3 else 0.0
            on = 1 if len(a) > 4 and a[4].strip() == "True" else 0
            if None not in (x, y, z, rot):
                for room in rooms:
                    levers.append((room, x, y, z, rot % 360.0, on))
        continue

    bm = button_re.search(line)
    if bm:
        a = [x.strip() for x in bm.group(1).split(",")]
        if len(a) >= 4:
            bid = BUTTON_TYPES.get(a[0], 0)
            x, y, z = ev(a[1]), ev(a[2]), ev(a[3])
            pitch = ev(a[4]) if len(a) > 4 else 0.0
            yaw = ev(a[5]) if len(a) > 5 else 0.0
            roll = ev(a[6]) if len(a) > 6 else 0.0
            locked = 1 if len(a) > 8 and a[8].strip() == "True" else 0
            if None not in (x, y, z, pitch, yaw, roll):
                for room in rooms:
                    buttons.append((room, bid, x, y, z, pitch, yaw, roll,
                                    locked))


def cf(v):
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


with open(OUT, "w") as f:
    f.write("/* Generated by vita/tools/extract_fixtures.py - do not edit.\n"
            " * Room levers and standalone buttons from FillRoom\n"
            " * (room-local raw units; Blitz euler degrees). */\n"
            "#ifndef VITA_GAME_ROOM_FIXTURES_H\n"
            "#define VITA_GAME_ROOM_FIXTURES_H\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    float x, y, z;\n"
            "    float rotDeg;      /* yaw of the base */\n"
            "    unsigned char on;  /* initial state */\n"
            "} RoomLeverDef;\n\n"
            "typedef struct {\n"
            "    const char *room;\n"
            "    unsigned char btnId; /* 0 default 1 keycard 2 keypad\n"
            "                            3 scanner 4 elevator */\n"
            "    float x, y, z;\n"
            "    float pitch, yaw, roll;\n"
            "    unsigned char locked;\n"
            "} RoomButtonDef;\n\n")
    f.write("static const RoomLeverDef ROOM_LEVERS[] = {\n")
    for room, x, y, z, rot, on in levers:
        f.write('    { "%s", %s, %s, %s, %s, %d },\n'
                % (room, cf(x), cf(y), cf(z), cf(rot), on))
    f.write("};\n\n")
    f.write("static const RoomButtonDef ROOM_BUTTONS[] = {\n")
    for room, bid, x, y, z, p, yw, rl, lk in buttons:
        f.write('    { "%s", %d, %s, %s, %s, %s, %s, %s, %d },\n'
                % (room, bid, cf(x), cf(y), cf(z), cf(p), cf(yw), cf(rl),
                   lk))
    f.write("};\n\n#endif\n")

print("levers:", len(levers), "buttons:", len(buttons))
