/* Host tool: generates vita/src/game/room_gen_data.h - the static data
 * the Blitz-exact map generator needs to replay CreateMap's RNG stream:
 *   1. per-template room-light draw sequences (AddLight in FillRoom's
 *      common tail draws 4 rnds for a sprite light, 1 for light_fix /
 *      spotlight), in RMesh entity file order;
 *   2. the red channel of the five forest heightmaps (PlaceForest's
 *      detail pass draws per pixel).
 * Run from the repo root:
 *   gcc -Ivita/src -o extract_gen_data vita/tools/extract_gen_data.c \
 *       vita/src/formats/rmesh.c vita/src/game/mapgen.c -lm
 *   ./extract_gen_data > vita/src/game/room_gen_data.h */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "formats/rmesh.h"
#include "game/mapgen.h"

#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#include "formats/stb_image.h"

int main(void) {
    RoomTemplateList tpls;
    if (!templatesLoad("Data/rooms.ini", &tpls)) {
        fprintf(stderr, "rooms.ini load failed\n");
        return 1;
    }
    printf("/* Generated by vita/tools/extract_gen_data.c - do not edit.\n"
           " * Per-template light draw sequences ('S' = sprite light, 4\n"
           " * RNG draws; '1' = light_fix/spotlight, 1 draw) in RMesh\n"
           " * entity order, plus the forest heightmap red channels. */\n"
           "#ifndef VITA_GAME_ROOM_GEN_DATA_H\n"
           "#define VITA_GAME_ROOM_GEN_DATA_H\n\n"
           "typedef struct { const char *room; const char *lights; }"
           " RoomLightSeq;\n\n"
           "static const RoomLightSeq ROOM_LIGHT_SEQS[] = {\n");
    for (unsigned i = 0; i < tpls.count; i++) {
        if (!tpls.items[i].meshPath) continue;
        char path[512];
        snprintf(path, sizeof(path), "GFX/Map/%s", tpls.items[i].meshPath);
        char err[256];
        RMesh *m = rmeshLoadFile(path, err, sizeof(err));
        if (!m) {
            fprintf(stderr, "skip %s: %s\n", path, err);
            continue;
        }
        char seq[1024];
        int n = 0;
        for (unsigned e = 0; e < m->entityCount && n < 1000; e++) {
            switch (m->entities[e].type) {
                case RMESH_ENTITY_LIGHT: seq[n++] = 'S'; break;
                case RMESH_ENTITY_LIGHT_FIX:
                case RMESH_ENTITY_SPOTLIGHT: seq[n++] = '1'; break;
                default: break;
            }
        }
        seq[n] = '\0';
        printf("    { \"%s\", \"%s\" },\n", tpls.items[i].name, seq);
        rmeshFree(m);
    }
    printf("};\n\n");

    static const char *MAPS[5] = {
        "GFX/Map/Forest/forest1h.png", "GFX/Map/Forest/forest2h.png",
        "GFX/Map/Forest/forest2Ch.png", "GFX/Map/Forest/forest3h.png",
        "GFX/Map/Forest/forest4h.png",
    };
    printf("#define FOREST_HMAP_W 30\n"
           "static const unsigned char FOREST_HMAP_RED[5][900] = {\n");
    for (int i = 0; i < 5; i++) {
        int w, h, comp;
        unsigned char *px = stbi_load(MAPS[i], &w, &h, &comp, 4);
        if (!px || w != 30 || h != 30) {
            fprintf(stderr, "heightmap %s load failed (%dx%d)\n",
                    MAPS[i], w, h);
            return 1;
        }
        printf("    {");
        for (int p = 0; p < 900; p++) {
            printf("%s%d", p ? "," : "", px[p * 4]);
        }
        printf("},\n");
        stbi_image_free(px);
    }
    printf("};\n\n#endif\n");
    return 0;
}
