/* Generated by vita/tools/extract_cameras.py - do not edit.
 * FillRoom's security cameras (room-local raw units; Blitz
 * degrees). pitch = head tilt, angle = head yaw base (added
 * to the room angle), turn = sweep amplitude (0 = static),
 * follow = track the player. The live monitor feed is not
 * ported. */
#ifndef VITA_GAME_ROOM_CAMERAS_H
#define VITA_GAME_ROOM_CAMERAS_H

typedef struct {
    const char *room;
    float x, y, z;
    float pitch, angle, turn;
    unsigned char follow;
} RoomCameraDef;

static const RoomCameraDef ROOM_CAMERAS[] = {
    { "room1_storage", -256.0f, 384.0f, 640.0f, 20.0f, 180.0f, 45.0f, 0 },
    { "cont1_005", 0.0f, 415.0f, 424.0f, 30.0f, 180.0f, 30.0f, 0 },
    { "cont1_173", -516.0f, 352.0f, 2143.0f, 20.0f, 270.0f, 45.0f, 0 },
    { "cont1_173_intro", -3940.0f, -32.0f, -1248.0f, 20.0f, 270.0f, 45.0f, 0 },
    { "cont1_205", -1152.0f, 900.0f, 176.0f, 0.0f, 90.0f, 0.0f, 0 },
    { "room2_closets", 184.0f, 704.0f, 952.0f, 20.0f, 130.0f, 40.0f, 0 },
    { "room2_js", 1646.0f, 435.0f, 193.0f, 20.0f, 30.0f, 30.0f, 0 },
    { "room2_sl", -159.0f, 384.0f, -929.0f, 20.0f, 315.0f, 0.0f, 0 },
    { "room2_tesla_lcz", 0.0f, 704.0f, -953.0f, 30.0f, 0.0f, 0.0f, 0 },
    { "room2_tesla_hcz", 0.0f, 704.0f, -953.0f, 30.0f, 0.0f, 0.0f, 0 },
    { "room2_tesla_ez", 0.0f, 704.0f, -953.0f, 30.0f, 0.0f, 0.0f, 0 },
    { "room2c_gw_lcz", -688.0f, 384.0f, 688.0f, 40.0f, 225.0f, 45.0f, 0 },
    { "room2c_gw_lcz", -112.0f, 384.0f, 112.0f, 40.0f, 45.0f, 45.0f, 0 },
    { "cont2c_066_1162_arc", -192.0f, 704.0f, 192.0f, 20.0f, 225.0f, 45.0f, 0 },
    { "room4_ic", 320.0f, 544.0f, -320.0f, 30.0f, 0.0f, 0.0f, 1 },
    { "room2_checkpoint_lcz_hcz", -192.0f, 704.0f, 960.0f, 20.0f, 225.0f, 0.0f, 0 },
    { "cont1_106", 768.0f, -5936.0f, 1632.0f, 45.0f, 315.0f, 20.0f, 0 },
    { "cont1_106", -1439.0f, -7664.0f, 1709.0f, 20.0f, 315.0f, 30.0f, 0 },
    { "cont1_895", -320.0f, 704.0f, 288.0f, 120.06f, 225.0f, 45.0f, 0 },
    { "room2_nuke", 1121.0f, 4191.0f, -306.0f, 20.0f, 90.0f, 45.0f, 0 },
    { "room2_test_hcz", 744.0f, -856.0f, 236.0f, 0.0f, 0.0f, 0.0f, 1 },
    { "cont2_008", 384.0f, -4654.0f, 1168.0f, 20.0f, 135.0f, 45.0f, 0 },
    { "cont2_409", -3635.0f, -3840.0f, 1729.0f, 20.0f, 100.0f, 45.0f, 0 },
    { "cont3_513", -450.0f, 448.0f, 250.0f, 20.0f, 135.0f, 0.0f, 0 },
    { "cont3_966", -355.0f, 450.0f, 321.0f, 30.0f, 315.0f, 0.0f, 0 },
    { "room2_checkpoint_hcz_ez", 192.0f, 704.0f, -960.0f, 20.0f, 45.0f, 0.0f, 0 },
    { "room1_lifts", 384.0f, 384.0f, -960.0f, 20.0f, 45.0f, 45.0f, 0 },
    { "room2_office_2", -475.0f, 385.0f, 305.0f, 20.0f, 225.0f, 30.0f, 0 },
    { "room2c_ez", -288.0f, 384.0f, 288.0f, 20.0f, 225.0f, 45.0f, 0 },
    { "room2c_2_ez", -288.0f, 384.0f, 288.0f, 20.0f, 225.0f, 45.0f, 0 },
    { "room2c_ec", -265.0f, 1280.0f, 105.0f, 20.0f, 45.0f, 45.0f, 0 },
    { "room3_ez", -320.0f, 384.0f, 512.0f, 20.0f, 225.0f, 45.0f, 0 },
    { "room3_4_ez", -320.0f, 384.0f, 512.0f, 20.0f, 225.0f, 45.0f, 0 },
    { "room4_2_ez", 0.0f, 384.0f, 0.0f, 20.0f, 225.0f, 45.0f, 1 },
};

#endif
