/* Generated by vita/tools/extract_decals.py - do not edit.
 * FillRoom's static CreateDecal splats (room-local raw
 * units; Blitz euler degrees; blend 1 alpha 2 multiply
 * 3 additive). */
#ifndef VITA_GAME_ROOM_DECALS_H
#define VITA_GAME_ROOM_DECALS_H

typedef struct {
    const char *room;
    unsigned char id;
    float x, y, z;
    float pitch, yaw, roll;
    float size, alpha;
    unsigned char blend;
} RoomDecalDef;

static const RoomDecalDef ROOM_DECALS[] = {
    { "cont1_005", 0, -362.0f, 0.005f, -420.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont1_173", 0, 272.0f, 0.005f, 2310.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont1_173", 0, 456.0f, 0.005f, 2183.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont1_173_intro", 20, -5062.0f, -1088.95f, -3614.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_js", 20, 103.0f, 0.005f, 161.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont2_012", 3, -784.0f, -767.99f, 640.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont2_1123", 6, -550.0f, 769.005f, 568.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont2_1123", 4, 180.0f, 769.005f, 797.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room3_storage", 3, 3438.0f, -5510.0f, 6294.0f, 0.0f, 270.0f, 0.0f, 0.3f, 1.0f, 1 },
    { "room3_storage", 7, 1083.0f, -5631.995f, 890.0f, 90.0f, 180.0f, 0.0f, 0.5f, 1.0f, 1 },
    { "room2_mt", 0, 64.0f, 0.005f, 144.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_shaft", 3, 1334.0f, -795.99f, -220.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont2c_096", 2, -1212.0f, -603.995f, 846.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "cont2c_096", 0, -1244.0f, -607.995f, 570.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_ic", 20, -711.0f, 0.005f, 140.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_scientists_2", 0, -712.0f, 0.005f, -72.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_scientists_2", 2, -712.0f, 0.01f, -72.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room2_scientists_2", 0, -336.0f, 0.01f, 0.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
    { "room3_office", 20, 236.0f, 0.005f, -68.0f, 90.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1 },
};

#endif
