/* Generated by vita/tools/extract_fixtures.py - do not edit.
 * Room levers and standalone buttons from FillRoom
 * (room-local raw units; Blitz euler degrees). */
#ifndef VITA_GAME_ROOM_FIXTURES_H
#define VITA_GAME_ROOM_FIXTURES_H

typedef struct {
    const char *room;
    float x, y, z;
    float rotDeg;      /* yaw of the base */
    unsigned char on;  /* initial state */
} RoomLeverDef;

typedef struct {
    const char *room;
    unsigned char btnId; /* 0 default 1 keycard 2 keypad
                            3 scanner 4 elevator */
    float x, y, z;
    float pitch, yaw, roll;
    unsigned char locked;
} RoomButtonDef;

static const RoomLeverDef ROOM_LEVERS[] = {
    { "cont1_205", 80.0f, 192.0f, -163.0f, 270.0f, 1 },
    { "cont1_914", -1012.0f, 192.0f, -976.0f, 180.0f, 0 },
    { "cont1_914", -1300.0f, 192.0f, -976.0f, 180.0f, 0 },
    { "room2_gw", 162.0f, 192.0f, -279.0f, 270.0f, 1 },
    { "room2_gw_2", 162.0f, 192.0f, -279.0f, 270.0f, 1 },
    { "room2_sl", -49.0f, 689.0f, 913.0f, 0.0f, 1 },
    { "room2_tesla_lcz", -367.0f, 192.0f, -212.0f, 270.0f, 1 },
    { "room2_tesla_hcz", -367.0f, 192.0f, -212.0f, 270.0f, 1 },
    { "room2_tesla_ez", -367.0f, 192.0f, -212.0f, 270.0f, 1 },
    { "room2_tesla_lcz", -367.0f, 192.0f, -132.0f, 270.0f, 1 },
    { "room2_tesla_hcz", -367.0f, 192.0f, -132.0f, 270.0f, 1 },
    { "room2_tesla_ez", -367.0f, 192.0f, -132.0f, 270.0f, 1 },
    { "cont2_012", 240.0f, -584.0f, -367.0f, 0.0f, 0 },
    { "room3_storage", 3096.0f, -5464.0f, 6569.0f, 0.0f, 0 },
    { "room3_storage", 1216.0f, -5464.0f, 3240.0f, 0.0f, 0 },
    { "cont1_035", 209.0f, 224.0f, -205.0f, 90.0f, 0 },
    { "cont1_035", 209.0f, 224.0f, -132.0f, 90.0f, 0 },
    { "cont1_106", -744.0f, -7908.0f, 3123.0f, 0.0f, 1 },
    { "cont1_106", -665.0f, -7908.0f, 3123.0f, 0.0f, 0 },
    { "cont1_895", -800.0f, 180.0f, -339.0f, 180.0f, 1 },
    { "room2_nuke", -497.0f, 4016.0f, -553.0f, 90.0f, 1 },
    { "room2_nuke", -497.0f, 4016.0f, -421.0f, 90.0f, 1 },
    { "room2_servers_hcz", -1260.0f, 234.0f, 753.0f, 0.0f, 0 },
    { "room2_servers_hcz", -917.0f, 164.0f, 899.0f, 0.0f, 0 },
    { "room2_servers_hcz", -837.0f, 152.0f, 887.0f, 0.0f, 0 },
    { "cont2_049", 865.0f, -3374.0f, -854.0f, 270.0f, 0 },
    { "cont2_049", -815.0f, -3400.0f, 1097.0f, 180.0f, 0 },
    { "room2c_ec", -239.0f, 1104.0f, 632.0f, 270.0f, 1 },
    { "room2c_ec", -239.0f, 1104.0f, 568.0f, 270.0f, 1 },
    { "room2c_ec", -239.0f, 1104.0f, 504.0f, 270.0f, 1 },
    { "room3_gw", 279.0f, 192.0f, 164.0f, 0.0f, 1 },
};

static const RoomButtonDef ROOM_BUTTONS[] = {
    { "cont1_173_intro", 0, -5448.0f, -912.0f, -3870.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "cont1_173_intro", 0, -6470.0f, -912.0f, -1964.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "cont1_173_intro", 0, -4090.0f, -912.0f, -2300.0f, 0.0f, 270.0f, 0.0f, 1 },
    { "cont1_914", 0, -1224.0f, 176.0f, -990.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "room2_gw", 1, -473.0f, 176.0f, -135.0f, 0.0f, 270.0f, 25.0f, 1 },
    { "room2_gw_2", 1, -473.0f, 176.0f, -135.0f, 0.0f, 270.0f, 25.0f, 1 },
    { "room2_gw", 1, -443.0f, 176.0f, -135.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "room2_gw_2", 1, -443.0f, 176.0f, -135.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "room2_test_lcz", 1, -994.0f, 176.0f, -456.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "room3_lcz", 1, -230.0f, 176.0f, 834.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "room2c_2_lcz", 1, -230.0f, 176.0f, 834.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "room2_checkpoint_lcz_hcz", 1, 1160.0f, 176.0f, 646.0f, 0.0f, 0.0f, 0.0f, 1 },
    { "room2_checkpoint_lcz_hcz", 1, 1160.0f, 176.0f, -645.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "cont1_106", 0, -337.0f, -7904.0f, 3136.0f, 0.0f, 0.0f, 0.0f, 0 },
    { "room2_shaft", 0, 1180.0f, 180.0f, -552.0f, 0.0f, 270.0f, 0.0f, 1 },
    { "cont2_049", 0, -314.0f, -3368.0f, -612.0f, 0.0f, 270.0f, 0.0f, 0 },
    { "cont2_409", 1, -4523.0f, -4068.0f, -2095.0f, 0.0f, 180.0f, 25.0f, 1 },
    { "cont2c_096", 1, -1399.0f, -432.0f, 596.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "cont2c_096", 1, -1089.0f, -432.0f, 544.0f, 0.0f, 0.0f, 0.0f, 1 },
    { "cont2c_096", 1, -247.0f, 176.0f, -608.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "cont2c_096", 1, -297.0f, 176.0f, -928.0f, 0.0f, 270.0f, 0.0f, 1 },
    { "cont2c_096", 1, -707.0f, -432.0f, 1117.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "cont2c_096", 1, -757.0f, -432.0f, 797.0f, 0.0f, 270.0f, 0.0f, 1 },
    { "room2_checkpoint_hcz_ez", 1, 1160.0f, 176.0f, 645.0f, 0.0f, 0.0f, 0.0f, 1 },
    { "room2_checkpoint_hcz_ez", 1, 1160.0f, 176.0f, -646.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "gate_b", 0, -5678.0f, -368.0f, -3986.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "gate_b", 0, 1707.0f, 182.0f, -4226.0f, 0.0f, 180.0f, 0.0f, 1 },
    { "gate_b", 0, 3226.0f, 182.0f, -5447.0f, 0.0f, 90.0f, 0.0f, 1 },
    { "gate_b", 0, 3974.0f, -144.0f, 5643.0f, 0.0f, 270.0f, 0.0f, 1 },
    { "gate_b", 0, 4039.0f, -753.0f, 6488.0f, 0.0f, 270.0f, 0.0f, 1 },
};

#endif
